# ===================================
# SO101 Installer Config
# ===================================

ENV_NAME=lerobot

PYTHON_VERSION=3.12

LEROBOT_VERSION=0.6.1

TORCH_VERSION=2.7.1

TORCHVISION_VERSION=0.22.1

TORCHAUDIO_VERSION=2.7.1

NUMPY_VERSION=2.2.6

SAFETENSORS_VERSION=0.6.2

SETUPTOOLS_VERSION=80.9.0

PACKAGING_VERSION=25.0
