# ==========================================
# SO101 Installer Version Lock
# ==========================================

#############################################
# Ubuntu
#############################################

SUPPORTED_UBUNTU_MIN=22.04
SUPPORTED_UBUNTU_MAX=26.04

#############################################
# Conda
#############################################

MINIFORGE_VERSION=25.3.1

#############################################
# Python
#############################################

PYTHON_VERSION=3.12

#############################################
# LeRobot
#############################################

LEROBOT_VERSION=0.6.1

#############################################
# Torch
#############################################

TORCH_VERSION=2.7.1

TORCHVISION_VERSION=0.22.1

TORCHAUDIO_VERSION=2.7.1

#############################################
# Python Packages
#############################################

NUMPY_VERSION=2.2.6

SAFETENSORS_VERSION=0.6.2

TQDM_VERSION=4.69.0

PACKAGING_VERSION=25.0

SETUPTOOLS_VERSION=80.9.0

PYSERIAL_VERSION=3.5

DRACCUS_VERSION=0.10.0

OPENCV_VERSION=4.12.0.88

RICH_VERSION=14.1.0

REQUESTS_VERSION=2.32.5

HF_HUB_VERSION=0.34.4

#############################################
# USB
#############################################

USB_GROUP=dialout

#############################################
# Workspace
#############################################

ENV_NAME=lerobot

WORKSPACE=$HOME/lerobot

DATASET_PATH=$HOME/datasets

#############################################
# Robot
#############################################

DEFAULT_FOLLOWER_PORT=/dev/ttyACM0

DEFAULT_LEADER_PORT=/dev/ttyACM1

#############################################
# Camera
#############################################

CAMERA_WIDTH=640

CAMERA_HEIGHT=480

CAMERA_FPS=30

#############################################
# Installer
#############################################

INSTALLER_VERSION=1.0.0

INSTALLER_NAME=SO101-OneClick-Installer
